### ISSUE TITLE
[TODO] Refactor `GIM` for documentation

### ISSUE THREAD

**Issue by sahilbhola14** [PinguDevTeam/ICF-MI-framework#20]
# Description of item
- [ ] (refactor): Update snake_case to camelCase
- [ ] (refactor) : Add docstrings
- [ ] (docs): Update docs on Sphinx

Correspondence: @sahilbhola14
